apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nmelekhov-certificate
spec:
  dnsNames:
  - 'nmelekhov.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: nmelekhov-cert